spring:
   datasource:
      url: jdbc:h2:tcp://localhost/C:/Java/h2/data/avadodb
      username: avado
      password: avado
      driver-class-name: org.h2.Driver

   jpa:
      hibernate:
         ddl-auto: create-drop
      properties:
         hibernate:
            ddl-auto: create-drop
         properties:
            hibernate:
               "[format_sql]": true
               "[show_sql]": true

   security:
      oauth2:
         client:
            registration:
               google:
                  client-id: 932221186527-3tbjc2hh6h5p2gqemiqvf2obis7itg1h.apps.googleusercontent.com
                  client-secret: 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
                  redirect-uri: "http://localhost:8085/login/oauth2/code/google"
            provider:
               google:
                  user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
                  user-name-attribute: email

logging:
   level:
      "[com.tutorial]": debug

jwt:
   secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

server:
   port: 8085

file:
  dir: c:/Temp\

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
