spring:
   datasource:
      url: jdbc:h2:tcp://localhost/C:/Java/H2/data/avadodb
      username: avado
      password: avado
      driver-class-name: org.h2.Driver

   jpa:
      hibernate:
         ddl-auto: create-drop
      properties:
         hibernate:
            format sql: true
            show sql: true

logging:
   level:
      com.tutorial: debug

jwt:
   secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

server:
   port: 8085

file:
  dir: c:/Temp\

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
