spring:
   datasource:
      url: jdbc:h2:tcp://localhost/c:/java/h2/data/avado
      username: avado
      password: avado
      driver-class-name: org.h2.Driver

   jpa:
      hibernate:
         ddl-auto: create-drop
      properties:
         hibernate:
            format sql: true
            show sql: true

logging:
   level:
      com.tutorial: debug

jwt:
   secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

server:
   port: 8085
